# ASH Config:
ash-config:
    compound-separator: ":"
    shell-executable: "/bin/zsh"
    confirm-execution: False

# Basic alias / command
openDevFolder:
    cmd: open ~/Documents/Dev

# Custom multi-line command
runServer:
    cmd: |
        x = find . -iname "main.py"
        python3 x

gitFullCommit:
    cmd: |
        git add .
        git commit -m "$1"
        git push -u origin

# Nested commands
scan:
    cmd: nmap $1 # Runs with `scan`
    subcmd:
        os:
            cmd: nmap -o $1 # Runs with `scan:os`
        port:
            cmd: nmap -sP $1 # Runs with `scan:port`
            subcmd:
                web:
                    cmd: nmap -sP $1 -p 80, 443
